### PR TITLE
USB Device

### PR DESCRIPTION
**Pull request by r4gus**
I've ported the usb bulk example (found in the rp2040 datasheet) to Zig. The Rust [implementation](https://github.com/cbiffle/rp2040-usb-device-in-one-file/blob/main/src/main.rs) of Cliff Biffle with all the comments helped a lot (I copied most of the comments; he did a great job explaining the code).

This is WIP but @MasterQ32 suggested that I open a draft PR.

The device code already works (see loop-back example); I'm currently working on raw HID support.

You can get some USB debug output over UART

### CODE REVIEW

**Comment by r4gus** [comment]
Related to issue #39

**Comment by r4gus** [comment]
The `usb_hid.zig` example now shows up as potential FIDO authenticator device, i.e., seems like one can configure a raw hid device, but there are still issues:

1. Wireshark tells me that the configuration descriptor is malformed
2. `lsusb -v` tells me that the report descriptors are ` ** UNAVAILABLE **` (but wireshark doesn't complain so maybe this is fine)
3. Setup request nr 6 is missing (device enumeration will hang for a few seconds)

```
$ fido2-token -L
/dev/hidraw1: vendor=0xcafe, product=0x0001 (Raspberry Pi Pico Test Device) <-- yay :)
```

**Comment by r4gus** [comment]
One can now use the pico as (raw hid) device. I'll further play with it over the weekend and try to use the CTAPHID protocol with the device impl.

@MasterQ32 @mattnite let me know what you think

**Comment by mattnite** [comment]
This is amazing! One request though, could you please move reusable USB code to this repo? https://github.com/ZigEmbeddedGroup/usb, that way we can take this work and use it on other devices. Add it as a submodule for now, later we'll use the zig package manager.

**Comment by r4gus** [comment]
> This is amazing! One request though, could you please move reusable USB code to this repo? https://github.com/ZigEmbeddedGroup/usb, that way we can take this work and use it on other devices. Add it as a submodule for now, later we'll use the zig package manager.

How do you want me to pass the usb module to the hal module (within `addEmbeddedExecutable`)? Should I add a `[]*Modules` field to `EmbeddedExecutableOptions` and then add all modules passed as dependencies to hal?

**Comment by r4gus** [comment]
~Never mind, hal/usb wont depend on the usb module. Mistakes on my part~

Code will be added to the microzig repo directly

**Comment by mattnite** [comment]
I think microzig needs updating and then this is ready to go

**Pull request merged**
